### ISSUE TITLE
500 Server error on wrong password.

### ISSUE THREAD

**Issue by allanhortle** [GrahamDumpleton/dyndns53#1]
Like the title says, I went to `/register_ip` and put in the wrong password combo. From there on in it was 500 server errors?

Any help would be heaps appreciated.

**Comment by GrahamDumpleton** [comment]
If you are doing that from a web browser then restart the browser to clear the cache of the login/password. This may presume that you didn't say remember password. If you did, you may have to see if the browser preferences has a way of clearing the remembered login information for the site.

I am not sure why though a wrong log/password would have cause a 500 server error in the first place though. I can't remember if exceptions are logged by default, probably not and you have to uncomment:

```
app.debug = True
```

in the dyndns53.py file to see what is happening to cause an exception to occur.
